### ISSUE TITLE
Question about clustered primary keys

### ISSUE THREAD

**Issue by paf31** [lykahb/groundhog#35]
Suppose I have three tables `A`, `B` and `C`, and the clustered primary key for `C` includes a `DefaultKey` for `B`, and similarly the clustered primary key for `B` includes a `DefaultKey` for `A`. I know that joins are not possible in general, but I would like to find all `C`s which correspond to a particular `DefaultKey` for `A`.

This is simple for two tables using `select`, but I can't find a way to do what I'd like with three tables.

Note that the `DefaultKey` for `C` contains all the fields for a `DefaultKey` for `A`, so this should be a simple `SELECT ... WHERE` involving only columns from `C`, but I don't know how to write the correct selector. I want something like: 

```haskell
select $ C_B ~> B_A ==. a_key
```

I get an error like

```text
Couldn't match type
    Selector (Key B (Unique BIdentifier) _)
with type
    Field BConstructor (Key A (Unique AIdentifier))
```

Maybe I could do this using a raw query or expression, if this is not directly possible?

**Comment by lykahb** [comment]
When you define a composite key set mkEmbedded to true. That will tell Groundhog to make key a proper embedded datatype and generate selectors. It is off by default to avoid cluttering the namespace

    keys:
      - name: someconstraint
        mkEmbedded: true

    select $ C_B ~> B_ASelector ==. a_key

**Comment by paf31** [comment]
Worked like a charm, thank you very much.

Also, thank you for this excellent library. It matches my use case perfectly.
