### ISSUE TITLE
Provide documentation for connection string format

### ISSUE THREAD

**Issue by matthiasbeyer** [lykahb/groundhog#40]
Could you please provide documentation how the connection strings must look like?

**Comment by matthiasbeyer** [comment]
I assume that the connection string looks the same for all backends then? So sqlite connection string is the same as for postgres? I can hardly believe this...?

**Comment by lykahb** [comment]
The connection string is specific for the database API. The extra documentation was added only for postgresql. Mysql accepts a documented object. Sqlite accepts just a filename.

**Comment by matthiasbeyer** [comment]
:+1:
