### ISSUE TITLE
Examples for getting on primary key?

### ISSUE THREAD

**Issue by GetContented** [lykahb/groundhog#46]
All the examples show inserting new values and then using that return value (which is a Key) to "get" the record back, but none of them explain how to construct, say a CustomerKey (from your examples) from scratch using an Integer value. Would you be able to amend them for that, because I'd like to be able to do that, and I'm pretty lost on the types around Key.

**Comment by lykahb** [comment]
You can convert between values using functions from *Field classes.

convert :: (SinglePersistField a, SinglePersistField b, PersistBackend m) => a -> m b
convert k = toSinglePersistValue k >>= fromSinglePersistValue

**Comment by GetContented** [comment]
Sorry, I don't see how that answers what I was asking... If I want to construct a Key (CustomerKey in my case) from, say 1 (this is exactly what I'm trying to do), how would I do this? (PersistInt64 1) doesn't work.

**Comment by lykahb** [comment]
First, it will help to look at the datatype definitions. You can do it either by loading your module to ghci or invoking ghc with flag -ddump-splices.

In fact, it is defined as `CustomerKey PersistValue`, so you can manually construct it as `CustomerKey (PersistInt64 1)`. The converting example would make a PersistValue from Int (the k argument), and then make a key from this PersistValue. Perhaps I should put this conversion example in the documentation.

**Comment by GetContented** [comment]
First, thank you for taking the time to reply.

However, I’ve tried that, and a bunch of other things. It doesn’t typecheck when I try to use it in getBy. It complains with the following error, if I try:

<interactive>:9:9:
    Couldn't match type ‘BackendSpecific’ with ‘Unique u0’
    Expected type: Key Customer (Unique u0)
      Actual type: Key Customer BackendSpecific
    In the second argument of ‘($)’, namely
      ‘CustomerKey (PersistInt64 1)’
    In the expression: getBy $ CustomerKey (PersistInt64 1)


http://www.getcontented.com.au/ - Amazing website creation service. Get a professional, distinguished yet highly affordable website today.
http://www.getcontented.com.au/flute_websites.html - website design & hosting service for flutists
Ph. 02 8005 0701

**Comment by lykahb** [comment]
Groundhog has two types of keys - autoincremented and unique. You can read more how it works at https://www.fpcomplete.com/user/lykahb/groundhog
The code fails because you are passing an autoincremented key to the function that takes unique keys. You can try some examples from https://github.com/lykahb/groundhog/tree/master/examples in ghci and see what types the expressions have.

**Comment by GetContented** [comment]
Yeah, I realise this. I’ve actually read *all* your documentation, and a reasonable amount of your code, but the types for uniques are beyond me.

I couldn’t find one single example of passing a unique key to getBy.

All I could find were examples of you creating an item (usually with insert) and then passing the resultant key into a get function… but that doesn’t help me to know how to create one from scratch.

Could you give me an example? It’d be *excellent* if you could add this to your examples, too… 

I’m actually *using* your example code to play with as I work out how to do this.

Julian


http://www.getcontented.com.au/ - Amazing website creation service. Get a professional, distinguished yet highly affordable website today.
http://www.getcontented.com.au/flute_websites.html - website design & hosting service for flutists
Ph. 02 8005 0701

**Comment by GetContented** [comment]
Note that all I'm trying to do is insert a single record in the database, then later read it out by its "id", which should (AFAICS) be the autoicrementing index.

However, maybe the problem is that the following TH doesn't allow access to that autoincrementing key from my code... would that be likely?

      mkPersist defaultCodegenConfig [groundhog|
      - entity: Customer               # Name of the datatype
        constructors:
          - name: Customer
            fields:
              - name: customerName
                dbName: name           # Set column name to "name" instead of "customerName"
      - entity: Product
      |]

**Comment by GetContented** [comment]
Actually, nevermind. I worked it out (somehow!) I needed to use "get" rather than "getBy" if I wanted to use the autoincrement key.

So this is what I did:

      withPostgresqlConn connStr $ runDbConn $ get (CustomerKey (PersistInt64 1))

I'd recommend putting that *somewhere* in the documentation.

**Comment by bitemyapp** [comment]
@GetContented thank you for being patient and hammering it out, sorry I hadn't had time to kick it around yet. I second getting it in the docs somewhere :+1: :smile:
