### ISSUE TITLE
How do I get the autokey for a record?

### ISSUE THREAD

**Issue by GetContented** [lykahb/groundhog#48]
I'm trying to create a test example codebase based around the basics example: https://github.com/lykahb/groundhog/blob/master/examples/basic.hs

I've created 10 or so records in the database. I also have some code that grabs them all out... now how do I take one of the Customer records and save it back into the database? How can I get the AutoKey?

I've looked through all the examples and most of the codebase. I can't find out how to do this.

Do I need to change the template haskell for mkPersist?

Please amend the examples so they make this obvious. This is a very common use case, such as creating a web app (which I'm doing), and you have a list of items, and you need to know which are which such that you edit the correct one, so you can save them back.

**Comment by lykahb** [comment]
This is rather a question than an issue. Haskell Cafe where more people will have a chance to answer is a better place.

The example https://github.com/lykahb/groundhog/blob/master/examples/projections.hs uses `project` to get the key along with the value.

project (AutoKeyField, YourConstructor) condition

If you need all entries  you can use `selectAll`

**Comment by GetContented** [comment]
Sorry about that, but it's an issue with the documentation. I found it really difficult to understand how to do a few simple things. Most of the simple things (like getting all the records out) are actually very clear.

I don't know what Haskell Cafe is. I'll google it. Thanks for your time. I'll close this issue as you don't seem to be interested in changing the documentation.

**Comment by GetContented** [comment]
Sorry if my comment sounded narky. I'd like to adjust the documentation so it's a bit easier to understand sometime, perhaps. I'm not sure if you're interested in this?
