### ISSUE TITLE
Add conversionFunction field to field config 

### ISSUE THREAD

**Issue by eamsden** [lykahb/groundhog#54]
Please add a 'conversionFunction' field which allows the end-developer to specify an isomorphism between the type of the field in the entity and a type which has an existing PersistField instance. This should also work if the type is [A] where A has a PersistField instance.

**Comment by lykahb** [comment]
Fixed with https://github.com/lykahb/groundhog/commit/e2061daea650bb62f217f6d86df7c4cca409204e
