### ISSUE TITLE
Hackage release for transformers-0.5

### ISSUE THREAD

**Issue by andrewthad** [lykahb/groundhog#61]
I can see that the master branch has already bumped the version bounds for `transformers`. It would be nice to have this change on hackage too.

**Comment by lykahb** [comment]
I will release the updated packages with ghc 8 and transformers soon.

**Comment by MichaelXavier** [comment]
Is there anything we can do to help move this along?

**Comment by lykahb** [comment]
I did changes to connection API in HEAD preparing for the pipes and conduit integration. They may not have been well-thought. I think about simplifying connections before this public release.

**Comment by MichaelXavier** [comment]
Was the change specifically for transformers a code change or would you be able to edit the package metadata on hackage to allow a greater transformers version?

**Comment by MichaelXavier** [comment]
I just noticed the ghc8 branch and that its travis suite is passing. Is this generally safe to use? Maybe that could get a release so folks on ghc8/newer transformers aren't stuck behind the other improvements.

**Comment by lykahb** [comment]
@MichaelXavier Yes, it is safe to use. I planned to make a couple minor changes before the release. I'll release it the next week.

**Comment by lykahb** [comment]
Released on Hackage
