### ISSUE TITLE
Help writing utility functions

### ISSUE THREAD

**Issue by pjones** [lykahb/groundhog#74]
I love Groundhog.  I've only been playing with it for a few days but it's helped me a lot so far.

The only real issue I've had is navigating the types and classes.  My type-level programming skills just aren't good enough yet.  So, I'd like to ask for some help.

First, how can I get this function to compile?  Right now I get a mess of GHC errors about overlapping instances.

```haskell
checkKey k = do
  n <- count (AutoKeyField ==. k)
  return $ if n == 1 then Just k else Nothing
```

(The point of this function is to verify a key exists in the database after converting some `Text` into an `AutoKey`.)

Second, do you have any recommendations on papers or other materials that would help me better understand Groundhog?  I'd be happy to repay the effort by writing more documentation for the project.  

Thank you.

**Comment by pjones** [comment]
I'm still working on this and *I think* I am getting closer to having a solution.  I read [Fun with Type Functions](https://wiki.haskell.org/Simonpj/Talk:FunWithTypeFuns) and have a better understanding of type  functions and the type equality operator (`~`).

Any utility function I write that uses a method from the `PersistBackendConn` class runs into this same issue, wanting access to the `Database.Groundhog.Instances.EntityConstr'` constructor, which isn't exported.  For example:

```haskell
checkKey :: ( PersistEntity v
            , PrimitivePersistField (Key v BackendSpecific)
            , PersistBackend m
            , DbDescriptor conn
            , ConnectionManager conn
            , PersistBackendConn conn
            , Conn m ~ conn
            )
         => Key v BackendSpecific
         -> m (Maybe (Key v BackendSpecific))
checkKey k = do
  n <- count (AutoKeyField ==. k)
  return $ if n == 1 then Just k else Nothing
```

Produces:

```
    • Could not deduce (Database.Groundhog.Instances.EntityConstr'
                          (IsSumType v0) c0)
        arising from a use of ‘count’
      from the context: (PersistEntity v,
                         PrimitivePersistField (Key v BackendSpecific),
                         PersistBackend m,
                         DbDescriptor conn,
                         ConnectionManager conn,
                         PersistBackendConn conn,
                         Conn m ~ conn)
        bound by the type signature for:
                   checkKey :: (PersistEntity v,
                                PrimitivePersistField (Key v BackendSpecific), PersistBackend m,
                                DbDescriptor conn, ConnectionManager conn, PersistBackendConn conn,
                                Conn m ~ conn) =>
                               Key v BackendSpecific -> m (Maybe (Key v BackendSpecific))
        at lib/Merkel/Util/Groundhog.hs:(106,1)-(114,70)
      The type variables ‘v0’, ‘c0’ are ambiguous
      These potential instances exist:
        instance [overlap ok] Database.Groundhog.Instances.EntityConstr'
                                HFalse c
          -- Defined in ‘Database.Groundhog.Instances’
        instance [overlap ok] Constructor c =>
                              Database.Groundhog.Instances.EntityConstr' HTrue c
          -- Defined in ‘Database.Groundhog.Instances’
```

Is there another constraint I should be adding to my type signatures?

**Comment by lykahb** [comment]
Hi pjones, thank you for your interest. The expressions were written to balance the flexibility and ability to infer the types. A win is that the users can use any valid type not having to annotate types on both sides of the expression. As a result, it works well with the specific types, but writing generic functions can be hard.

I've written a similar function before to compare a field to null https://github.com/lykahb/groundhog/blob/master/groundhog/Database/Groundhog/Expression.hs#L165 Your case is more complex and I don't see a quick solution for it.

**Comment by pjones** [comment]
Thank you @lykahb.  For that particular function I decided to just use `get` after converting some text into a `Key`.

However, I have several other utility functions for which I cannot write type signatures.  GHC can generate a signature for me, but it includes the private `Database.Groundhog.Instances.EntityConstr'` type.  For example:

```haskell
selectOne opts = MaybeT (listToMaybe <$> select (opts `limitTo` 1))
```

Any suggestions?

**Comment by lykahb** [comment]
GHC often infers the types with the low-level definitions. A better starting point for selectOne is the type of select. So, after modifying the type to reflect that limitTo was used, it is:
```haskell
selectOne :: (PersistEntity v, 
              EntityConstr v c,
              HasSelectOptions opts conn (RestrictionHolder v c), 
              PersistBackend m, 
              Conn m ~ conn, 
              HasLimit opts ~ HFalse) => opts -> MaybeT m v
selectOne opts = MaybeT (listToMaybe <$> select (opts `limitTo` 1))
```

**Comment by pjones** [comment]
Awesome!  Thank you.
