### ISSUE TITLE
Sum types with common fields

### ISSUE THREAD

**Issue by blaxill** [lykahb/groundhog#77]
Sum types with common fields appear not to work, e.g.:

```haskell
data Foo = A { bar :: Int } | B { bar :: Int, unique :: Int}

mkPersist defaultCodegenConfig [groundhog|
- entity: Foo
|]

```

When using the quasiquoting, it fails due to generating multiple bar field constructors:

```
Main.hs:26:1: error:
        Multiple declarations of ‘BarField’
        Declared at: Main.hs:26:1
                     Main.hs:26:1

```

Also using `mkPersist` without quasiquoting fails again due to duplicate constructors. I'd expect it to succeed and generate a schema sharing the common field for different constructors.

Is there away around this without modifying the data structure (which in my case is deep in a dependency)?

**Comment by lykahb** [comment]
You can change the name in the mapping declaration with `exprName`.
https://hackage.haskell.org/package/groundhog-th-0.8.0.1/docs/Database-Groundhog-TH.html

**Comment by blaxill** [comment]
Thanks, I had seen the exprName but incorrectly assumed it modified the dbName.
