### ISSUE TITLE
What needs to be done to get a ghc 8.4 compatible release?

### ISSUE THREAD

**Issue by DougBurke** [lykahb/groundhog#80]
With ghc 8.6 just around the corner, I was wondering what needed to be done to get a ghc 8.4 compatible release?

**Comment by lykahb** [comment]
Thanks for the reminder! It looks like 8.4 works in HEAD. I'll release it on Hackage.

**Comment by DougBurke** [comment]
It's been added to LTS 12.16 - https://www.stackage.org/lts-12.16
